services:
  # Service Web pour l'application Django avec Daphne (ASGI/WebSockets)
  - type: web
    name: linguameet
    runtime: docker
    plan: free
    region: oregon  # Même région que la base de données
    dockerfilePath: ./Dockerfile
    envVars:
      # Django Settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      
      # Database
      - key: DATABASE_URL
        fromDatabase:
          name: linguameet-db
          property: connectionString
      
      # Admin Credentials (IMPORTANT: Changez ces valeurs!)
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@linguameet.com
      - key: ADMIN_PASSWORD
        sync: false  # À définir manuellement dans le dashboard Render
      
      # Pipeline de Traduction
      - key: USE_FREE_PREMIUM
        value: True
      
      # Google Gemini API (Traduction)
      - key: GEMINI_API_KEY
        sync: false  # À définir manuellement
      
      # Google Cloud Credentials (Speech-to-Text et Text-to-Speech)
      # Note: Pour Render, vous devrez encoder le fichier JSON en base64
      # Commande: base64 -w 0 credentials/google-cloud-key.json
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false  # Contenu JSON encodé en base64
      
      # Allowed Hosts
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      
      # CSRF Trusted Origins
      - key: CSRF_TRUSTED_ORIGINS
        value: https://linguameet-klg6.onrender.com
    
    healthCheckPath: /about

databases:
  # Base de données PostgreSQL gratuite
  - name: linguameet-db
    databaseName: linguameet
    plan: free
    region: oregon  # Même région que l'app pour réduire la latence
