services:
  # Service Web pour l'application Django avec Daphne (ASGI/WebSockets)
  - type: web
    name: linguameet
    runtime: docker
    plan: free
    region: frankfurt  # Europe (ou oregon pour USA)
    dockerfilePath: LINGUAMEET/Dockerfile
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DATABASE_URL
        fromDatabase:
          name: linguameet-db
          property: connectionString
    healthCheckPath: /healthz

databases:
  # Base de données PostgreSQL gratuite
  - name: linguameet-db
    databaseName: linguameet
    plan: free
    region: frankfurt  # Même région que l'app pour réduire la latence
