# Generated by Django 5.2.3 on 2025-06-28 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de la salle"),
                ),
                (
                    "langue_par_defaut",
                    models.CharField(
                        default="fr", max_length=10, verbose_name="Langue par défaut"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Salle de conférence",
                "verbose_name_plural": "Salles de conférence",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom du participant"),
                ),
                (
                    "langue_souhaitée",
                    models.CharField(
                        default="en",
                        max_length=10,
                        verbose_name="Langue de réception souhaitée",
                    ),
                ),
                (
                    "langue_parole",
                    models.CharField(
                        default="fr", max_length=10, verbose_name="Langue de parole"
                    ),
                ),
                ("socket_id", models.CharField(blank=True, max_length=100, null=True)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("date_join", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
                ("micro_actif", models.BooleanField(default=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="conference.room",
                        verbose_name="Salle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
    ]
