# Generated by Django 5.2.3 on 2025-06-28 20:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_text", models.TextField(verbose_name="Texte original")),
                ("translated_text", models.TextField(verbose_name="Texte traduit")),
                (
                    "original_language",
                    models.CharField(max_length=10, verbose_name="Langue originale"),
                ),
                (
                    "target_language",
                    models.CharField(max_length=10, verbose_name="Langue cible"),
                ),
                (
                    "audio_file",
                    models.FileField(
                        upload_to="conversations/%Y/%m/%d/",
                        verbose_name="Fichier audio",
                    ),
                ),
                (
                    "audio_duration",
                    models.FloatField(
                        default=0.0, verbose_name="Durée audio (secondes)"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Archivé"),
                ),
                (
                    "listener",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listened_conversations",
                        to="conference.participant",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="conference.room",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speeches",
                        to="conference.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de conversation",
                "verbose_name_plural": "Historiques de conversations",
                "ordering": ["-timestamp"],
            },
        ),
    ]
