# Generated by Django 5.2.3 on 2025-10-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0002_conversationhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="video_actif",
            field=models.BooleanField(default=True),
        ),
    ]
