# Generated by Django 5.0.1 on 2025-10-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0003_participant_video_actif"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="langue_parole",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="langue_souhaitée",
        ),
        migrations.AddField(
            model_name="participant",
            name="langue",
            field=models.CharField(
                default="fr",
                max_length=10,
                verbose_name="Langue du participant (parle et écoute)",
            ),
        ),
    ]
