# Generated by Django 5.0.1 on 2025-10-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0004_remove_participant_langue_parole_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="langue",
        ),
        migrations.AddField(
            model_name="participant",
            name="langue_parole",
            field=models.CharField(
                default="fr",
                max_length=10,
                verbose_name="Langue que le participant parle",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="langue_souhaitée",
            field=models.CharField(
                default="en",
                max_length=10,
                verbose_name="Langue que le participant souhaite recevoir",
            ),
        ),
    ]
